version: '3.8'

services:
  postgres:
    container_name: process-file
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: process-file
    volumes:
      - postgres_data:/bitnami/postgresql

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - '5672:5672'  # Porta para a comunicação AMQP
      - '15672:15672'  # Porta para acessar o painel de administração
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf  # Monta o arquivo de configuração

  redis:
    container_name: redis
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - redis_data:/bitnami/redis

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
